
import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import paneles.CambiaPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Charlie Rivera
 */
public class Principal extends javax.swing.JFrame {
    private String usuario_t;
    Login mod;
    public Principal() {
        initComponents();
       setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);
         this.setResizable(false);
         this.uno.setSelected(true);
        // new CambiaPanel(panelp, new PortadaAudioImpact());
    
   }
    public Principal(Login mod){
      initComponents();
        this.mod= mod;
//        if(mod.getTipo_usuario().equals("admin")){
//            System.out.println("Usuario Administrador");
            setUsuario_t(mod.getTipo_usuario());
//        }
    }
        //Método para obtener el tipo de usuario
    public String getUsuario_t() {
        return usuario_t;
    }
        //Método para enviar el tipo de usuario
    public void setUsuario_t(String usuario_t) {
        this.usuario_t = usuario_t;
    }
    
    private void cerrar(){
        
        String botones[] = {"cerrar","cancelar" };
        int eleccion=JOptionPane.showConfirmDialog(this,"¿Desea cerrar el programa?","Advertencia",JOptionPane.YES_OPTION);
   if(eleccion==JOptionPane.YES_OPTION){
       System.exit(0);
   }else if (eleccion==JOptionPane.NO_OPTION){
       
   System.out.println("se cancelo");
   }
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        uno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        uno1 = new javax.swing.JButton();
        lateral = new javax.swing.JPanel();
        one = new rsbuttom.RSButtonMetro();
        two = new rsbuttom.RSButtonMetro();
        three = new rsbuttom.RSButtonMetro();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        five = new rsbuttom.RSButtonMetro();
        five1 = new rsbuttom.RSButtonMetro();
        panelp = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(241, 241, 241));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 133, 186));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IconoSalir_1.png"))); // NOI18N
        uno.setBorder(null);
        uno.setContentAreaFilled(false);
        uno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        jPanel1.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 31, 40));

        jLabel3.setFont(new java.awt.Font("Decker", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Audio Impact - Cabo & USA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 50));

        uno1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        uno1.setBorder(null);
        uno1.setContentAreaFilled(false);
        uno1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uno1ActionPerformed(evt);
            }
        });
        jPanel1.add(uno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 31, 40));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 860, 70));

        lateral.setBackground(new java.awt.Color(35, 40, 45));
        lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        one.setBackground(new java.awt.Color(35, 40, 45));
        one.setForeground(new java.awt.Color(160, 165, 169));
        one.setText("    Clientes");
        one.setColorHover(new java.awt.Color(0, 115, 170));
        one.setColorNormal(new java.awt.Color(35, 40, 45));
        one.setColorTextNormal(new java.awt.Color(160, 165, 169));
        one.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        one.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                oneMousePressed(evt);
            }
        });
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        lateral.add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 50));

        two.setBackground(new java.awt.Color(35, 40, 45));
        two.setForeground(new java.awt.Color(160, 165, 169));
        two.setText("    Proyectos");
        two.setColorHover(new java.awt.Color(0, 115, 170));
        two.setColorNormal(new java.awt.Color(35, 40, 45));
        two.setColorTextNormal(new java.awt.Color(160, 165, 169));
        two.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        two.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoMouseClicked(evt);
            }
        });
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        lateral.add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 180, 50));

        three.setBackground(new java.awt.Color(35, 40, 45));
        three.setForeground(new java.awt.Color(160, 165, 169));
        three.setText("    Cotizaciones");
        three.setColorHover(new java.awt.Color(0, 115, 170));
        three.setColorNormal(new java.awt.Color(35, 40, 45));
        three.setColorTextNormal(new java.awt.Color(160, 165, 169));
        three.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        three.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeMouseClicked(evt);
            }
        });
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        lateral.add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, 50));

        jPanel6.setBackground(new java.awt.Color(50, 55, 60));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(160, 165, 169));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(128, 128, 131));
        jLabel6.setText("Inicio");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 50));

        lateral.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        five.setBackground(new java.awt.Color(35, 40, 45));
        five.setForeground(new java.awt.Color(160, 165, 169));
        five.setText("    Salir");
        five.setColorHover(new java.awt.Color(0, 115, 170));
        five.setColorNormal(new java.awt.Color(35, 40, 45));
        five.setColorTextNormal(new java.awt.Color(160, 165, 169));
        five.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        five.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveMouseClicked(evt);
            }
        });
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        lateral.add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 180, 50));

        five1.setBackground(new java.awt.Color(35, 40, 45));
        five1.setForeground(new java.awt.Color(160, 165, 169));
        five1.setText("    Almacén");
        five1.setColorHover(new java.awt.Color(0, 115, 170));
        five1.setColorNormal(new java.awt.Color(35, 40, 45));
        five1.setColorTextNormal(new java.awt.Color(160, 165, 169));
        five1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        five1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        five1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                five1MouseClicked(evt);
            }
        });
        five1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five1ActionPerformed(evt);
            }
        });
        lateral.add(five1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 50));

        jPanel4.add(lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 730));

        panelp.setBackground(new java.awt.Color(255, 255, 255));
        panelp.setLayout(new javax.swing.BoxLayout(panelp, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(panelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 680, 720));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 861, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
         cerrar();
    }//GEN-LAST:event_unoActionPerformed

    private void uno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uno1ActionPerformed
       int posicion = this.lateral.getX();
       if(posicion > -1){
           Animacion.Animacion.mover_izquierda(0, -188, 2, 2, lateral);
           Animacion.Animacion.mover_izquierda(200, -0, 2, 2, panelp);
       }else{
           Animacion.Animacion.mover_derecha(-188, 0, 2, 2, lateral);
           Animacion.Animacion.mover_derecha(-0, 150, 2, 2, panelp);
       }
       
       
      
       
    }//GEN-LAST:event_uno1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
    }//GEN-LAST:event_formWindowClosing

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        new CambiaPanel(panelp, new Consulta_clientes(Principal.this));
        
        if (this.one.isSelected()) {
            this.one.setColorNormal(new Color(0,115,170));
            this.one.setColorHover(new Color(0, 115, 170));
            this.one.setColorPressed(new Color(241,241,241));
            this.one.setColorTextNormal(new Color(255,255,255));
             
        } else{
            this.one.setColorNormal(new Color(0,115,170));
            this.one.setColorHover(new Color(0,115,170));
            this.one.setColorPressed(new Color(241,241,241));
             this.one.setColorTextNormal(new Color(255,255,255));
        }
    }//GEN-LAST:event_oneActionPerformed

    private void oneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMousePressed
//        this.one.setSelected(true);
//         this.two.setSelected(false);
//          this.three.setSelected(false);
//           this.four.setSelected(false);
//            this.five.setSelected(false);
    }//GEN-LAST:event_oneMousePressed

    private void twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseClicked
       
//       this.one.setSelected(true);
//         this.two.setSelected(false);
//          this.three.setSelected(false);
//           this.four.setSelected(false);
//            this.five.setSelected(false);
    }//GEN-LAST:event_twoMouseClicked

    private void threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseClicked
      new CambiaPanel(panelp, new cotizaciones());
    }//GEN-LAST:event_threeMouseClicked

    private void fiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseClicked
        new CambiaPanel(panelp, new Consulta_productos());
        
    }//GEN-LAST:event_fiveMouseClicked

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threeActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        new CambiaPanel(panelp, new Consulta_proyecto(Principal.this));
//        if (this.one.isSelected()) {
//            this.one.setColorNormal(new Color(0,115,170));
//            this.one.setColorHover(new Color(0, 115, 170));
//            this.one.setColorPressed(new Color(241,241,241));
//            this.one.setColorTextNormal(new Color(255,255,255));
//             
//        } else{
//            this.one.setColorNormal(new Color(0,115,170));
//            this.one.setColorHover(new Color(0,115,170));
//            this.one.setColorPressed(new Color(241,241,241));
//            this.one.setColorTextNormal(new Color(255,255,255));
//        }
    }//GEN-LAST:event_twoActionPerformed

    private void oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseClicked
       
    }//GEN-LAST:event_oneMouseClicked

    private void five1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_five1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_five1MouseClicked

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        Login log =new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fiveActionPerformed

    private void five1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five1ActionPerformed
    new CambiaPanel(panelp, new Consulta_productos(Principal.this));
    }//GEN-LAST:event_five1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static rsbuttom.RSButtonMetro five;
    public static rsbuttom.RSButtonMetro five1;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel6;
    public static javax.swing.JPanel lateral;
    public static rsbuttom.RSButtonMetro one;
    public static javax.swing.JPanel panelp;
    public static rsbuttom.RSButtonMetro three;
    public static rsbuttom.RSButtonMetro two;
    public static javax.swing.JButton uno;
    public static javax.swing.JButton uno1;
    // End of variables declaration//GEN-END:variables

    private void setDefaultCloseOperation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
